services:
  postgres:
    image: postgres:16-alpine
    container_name: nomba-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nomba_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nomba-network

  redis:
    image: redis:7-alpine
    container_name: nomba-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - nomba-network

volumes:
  postgres_data:
  redis_data:

networks:
  nomba-network:
    driver: bridge
